import pygame as pg
from pathlib import Path

pg.init()

BASE_DIR = Path(__file__).resolve().parent

# ============ SCREEN SIZE ============
WIDTH, HEIGHT = 1120, 800

PADDING_SMALL, PADDING_BIG = 18, 44

# ============ START SCREEN ============
START_TITLE_Y = 270
START_BUTTONS_Y = 400

# ============ SETTINGS LAYOUT ============
SETTINGS_TITLE_Y_OFFSET = 66
SETTINGS_SIDE_PADDING = 44
SETTINGS_BOTTOM_PADDING = 20
SETTINGS_COLUMN_GAP = 28
SETTINGS_CONTENT_TOP_GAP = 18
SETTINGS_SECTION_GAP = 28
SETTINGS_SECTION_TITLE_GAP = 16
SETTINGS_DIFFICULY_GAP = 10
SETTINGS_NAME_SECTION_HEIGHT = 188
TEXT_FIELD_HEIGHT = 64
SETTINGS_BORDER = 45
SETTINGS_TEXT_OFFSET_X = 14

# ============ ROOM GRID ============
GRID_SIZES = {
    "easy": (3, 2),
    "medium": (6, 4),
    "hard": (9, 6),
}
MEDIUM_GRID_W, MEDIUM_GRID_H = GRID_SIZES["medium"]

# ============ PATHS ============
ASSETS_PATH = BASE_DIR / "assets"
IMAGES_PATH = ASSETS_PATH / "images"
FONTS_PATH = ASSETS_PATH / "fonts"
MUSIC_PATH = ASSETS_PATH / "music"
